#!/usr/bin/expect
set timeout
set host [lrange $argv 0 0]
set username [lrange $argv 1 1]
set password [lrange $argv 2 2]
set src_file [lrange $argv 3 3]
set dest_file [lrange $argv 4 4]

puts $host
puts $username
puts $password
puts $src_file
puts $dest_file
spawn scp $src_file $username@$host:$dest_file
 expect {
 "(yes/no)?"
  {
    send "yes\n"
    expect "*assword:" { send "$password\n"}
  }
 "*assword:"
  {
    send "$password\n"
  }
}
expect "100%"
expect eof